[package]
name = "text-calendar"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
dirs = "4.0"
chrono = "0.4"
